# permissions for end users to view secretsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secretsync-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: secret-sync-operator
    app.kubernetes.io/part-of: secret-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretsync-viewer-role
rules:
- apiGroups:
  - sync.samir.io
  resources:
  - secretsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.samir.io
  resources:
  - secretsyncs/status
  verbs:
  - get
